added styles
last-in-japan/spilnyk_client pull request #3
Opened 2021-06-20 17:55 UTC by Trall2591

2021-06-20 17:56 UTC, sam-sobi-otaman requested changes

2021-06-20 17:56 UTC, sam-sobi-otaman commented on assets/header.scss
> +
Delete empty line

2021-07-01 20:01 UTC, sam-sobi-otaman requested changes

2021-07-27 04:50 UTC, last-in-japan approved these changes

2021-07-27 04:51 UTC, merged